# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payment.proto',
  package='payment',
  syntax='proto3',
  serialized_options=_b('\n\017io.grpc.paymentB\014PaymentProtoP\001'),
  serialized_pb=_b('\n\rpayment.proto\x12\x07payment\":\n\x0ePaymentRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\"\x1f\n\x0cPaymentReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x06\n\x04Void2\x89\x01\n\x0ePaymentService\x12\x37\n\x0bSendPayment\x12\x17.payment.PaymentRequest\x1a\r.payment.Void\"\x00\x12>\n\nGetPayment\x12\x17.payment.PaymentRequest\x1a\x15.payment.PaymentReply\"\x00\x42!\n\x0fio.grpc.paymentB\x0cPaymentProtoP\x01\x62\x06proto3')
)




_PAYMENTREQUEST = _descriptor.Descriptor(
  name='PaymentRequest',
  full_name='payment.PaymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='payment.PaymentRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='payment.PaymentRequest.transaction_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=84,
)


_PAYMENTREPLY = _descriptor.Descriptor(
  name='PaymentReply',
  full_name='payment.PaymentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='payment.PaymentReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=117,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='payment.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['PaymentRequest'] = _PAYMENTREQUEST
DESCRIPTOR.message_types_by_name['PaymentReply'] = _PAYMENTREPLY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentRequest = _reflection.GeneratedProtocolMessageType('PaymentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payment.PaymentRequest)
  })
_sym_db.RegisterMessage(PaymentRequest)

PaymentReply = _reflection.GeneratedProtocolMessageType('PaymentReply', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTREPLY,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payment.PaymentReply)
  })
_sym_db.RegisterMessage(PaymentReply)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payment.Void)
  })
_sym_db.RegisterMessage(Void)


DESCRIPTOR._options = None

_PAYMENTSERVICE = _descriptor.ServiceDescriptor(
  name='PaymentService',
  full_name='payment.PaymentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=128,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPayment',
    full_name='payment.PaymentService.SendPayment',
    index=0,
    containing_service=None,
    input_type=_PAYMENTREQUEST,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPayment',
    full_name='payment.PaymentService.GetPayment',
    index=1,
    containing_service=None,
    input_type=_PAYMENTREQUEST,
    output_type=_PAYMENTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYMENTSERVICE)

DESCRIPTOR.services_by_name['PaymentService'] = _PAYMENTSERVICE

# @@protoc_insertion_point(module_scope)
